### ISSUE TITLE
ERR_CONNECTION_REFUSED with example using docker-compose

### ISSUE THREAD

**Issue by mattcanty** [cnadiminti/docker-aws-sam-local#4]
Hi,

Great looking package, having a bit of trouble getting off the ground though...

```
version: '3'
services:
  aws-sam-local:
    image: cnadiminti/aws-sam-local
    command: local start-api --docker-volume-basedir "$PWD/example" --host 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./example:/var/opt
```

```
Mounting index.handler (nodejs6.10) at http://0.0.0.0:3000/ [OPTIONS GET HEAD POST PUT DELETE TRACE CONNECT]
Mounting static files from /Users/matthewcanty/dev/commute/example/public at /

You can now browse to the above endpoints to invoke your functions.
You do not need to restart/reload SAM CLI while working on your functions,
changes will be reflected instantly/automatically. You only need to restart
SAM CLI if you update your AWS SAM template.
```
![image](https://user-images.githubusercontent.com/2089581/35475117-ba6ff2b0-0390-11e8-9dc5-796800a05155.png)
